title: "The Butler"
baseline: "Your blogging assistant."
description: "A ready to use static blog, powered by Cecil."
keywords: "Cecil, Static Site Generator, SSG"
author: "Arnaud Ligny"
baseurl: "/"
canonicalurl: true
theme: "garth"
date:
  format: "j F Y"
  timezone: "Europe/Paris"
output:
  formats:
    netlify_redirects:
      mediatype: "text/plain"
      extension: ""
virtualpages:
  - path: admin
    layout: admin/index
    output: html
    title: "Content Manager (Netlify CMS)"
  - path: _redirects
    output: netlify_redirects
netlify:
  cms:
    path: "admin"
    version: "latest"
  identity:
    version: "v1"
optimize:
  enabled: true
